version: '2'
services:
  influxdb:
    image: influxdb:1.8
    ports:
      - '8086:8086'
    volumes:
      - ./influxdb-storage/:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USER}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
  chronograf:
    image: chronograf:latest
    ports:
      - '8888:8888'
    volumes:
      - ./chronograf-storage/:/var/lib/chronograf
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_USERNAME=${INFLUXDB_USER}
      - INFLUXDB_PASSWORD=${INFLUXDB_PASSWORD}
      - INFLUX_TOKEN=W36eVLyGP15hD2-mkLSWoeWxnCewuHUR0UpsqUNHDhdh-2zQYQPxqpEiOYFew82Vap1bsjfAiFJ7DhNRj14BuQ==
  grafana:
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    user: root:root
    volumes:
      - ./grafana-storage/:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
  nodered:
    image: nodered/node-red:latest
    ports:
      - '1880:1880'
    user: root:root
    volumes:
      - ./node_red_data/:/data
volumes:
  influxdb-storage:
  chronograf-storage:
  grafana-storage:
  node_red_data:
